version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
      POSTGRES_DB: ${LOCAL_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    networks:
      - db_server_network

volumes:
  pgdata:

networks:
  db_server_network:
    driver: bridge